name: 'Build Documentation'
description: 'Build project documentation using Sphinx'
inputs:
  docs-path:
    description: 'Path to documentation source'
    required: false
    default: 'docs'
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: |
        pip install sphinx sphinx-rtd-theme
        cd ${{ inputs.docs-path }}
        make html
      shell: bash